# Generated by Django 3.1.7 on 2021-04-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20210323_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catwise',
            name='BYW',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='CatWISESpec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='CatWISESpecSrc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='FoundInSearch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='JMagSrc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='OnSpitzerPrg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='RaDEC',
            field=models.CharField(max_length=50),
        ),
    ]
